name: Events Demo 1
on: 
  pull_request:
    types: 
      - opened
      # - closed
    branches: 
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
      # developer-1
  workflow_dispatch:
  push: 
    branches: 
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
      # developer-1
    paths-ignore:
      - '.github/workflows/*'
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install depencencies
        run: |
          cd events-deep-dive
          npm ci
      - name: Test code
        run: |
          cd events-deep-dive
          npm run test 
      - name: Build code
        run: |
          cd events-deep-dive
          npm run build
      - name:
        run: echo "Deploying..."