name: Deployment Exercise 1
# on: push
on: workflow_dispatch
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd third-action-react-demo 
          npm ci
      - name: Lint
        run: |
          cd third-action-react-demo 
          npm run lint 
      - name: Test code
        run: |
          cd third-action-react-demo 
          npm run test 
      - name: Deployment
        run: echo "Deploying..."