name: Deploy Project
on: push
jobs: 
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd second-action-react-demo
          rm -rf node_modules  # Clean any cached modules
          npm ci --verbose  # Add verbose flag for debugging
      - name: Run tests
        run: |
          cd second-action-react-demo
          npm test
  deploy:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd second-action-react-demo
          rm -rf node_modules  # Clean any cached modules
          npm ci --verbose  # Add verbose flag for debugging
      - name: Build project
        run: |
          cd second-action-react-demo
          npm run build
      - name: Deploy
        run: echo "Deploying ..."