name: Deployment Exercise 1
on: push
jobs:
  deploy: 
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd second-action-react-demo 
          npm ci
      - name: Lint
        run: |
          cd second-action-react-demo 
          npm run lint 
      - name: Test code
        run: |
          cd second-action-react-demo 
          npm run test 
      - name: Deployment
        run: echo "Deploying..."