name: Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd third-action-react-demo 
          npm ci
      - name: Lint
        run: |
          cd third-action-react-demo 
          npm run lint
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd third-action-react-demo 
          npm ci
      - name: Test code
        run: |
          cd third-action-react-demo 
          npm run test 
  deploy: 
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd third-action-react-demo 
          npm ci
      - name: Deployment
        run: echo "Deploying..."