name: Using Reusable Workflow
on:
  push:
    branches:
      - main
# on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: exec-flow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd exec-flow
          npm ci
      - name: Lint code
        run: |
          cd exec-flow
          npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: exec-flow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd exec-flow
          npm ci
      - name: Test code
        id: run-tests
        run: |
          cd exec-flow
          npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: exec-flow/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd exec-flow
          npm ci
      - name: Build website
        id: build-website
        run: |
          cd exec-flow
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: exec-flow/dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with: 
      artifact-name:: dist-files
  report:
    needs: [lint, deploy]
    runs-on: ubuntu-latest  
    steps: 
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ github }}"


